### ISSUE TITLE
to use the net

### ISSUE THREAD

**Issue by HKCaesar** [GunhoChoi/FusionNet-Pytorch#2]
Dear author ,
      I have trouble with  in main.py ---" fusion = nn.DataParallel(FusionNet()).cuda()".It looks like that the FusionNet   is not defined in FusionNet.py?What to do with it ?
Thanks!

**Comment by GunhoChoi** [comment]
oh there was a naming error. 
It's working now and if you also want test u-net, you can refer to 
https://github.com/GunhoChoi/Kind_PyTorch_Tutorial/tree/master/12_Semantic_Segmentation 

thx for letting me recognize the error :)
