### ISSUE TITLE
NameError: name 'FusionNet' is not defined

### ISSUE THREAD

**Issue by emindeniz** [GunhoChoi/FusionNet-Pytorch#3]
Hello,
I have run main.py without any error. However I am getting the following error when I am trying to run main_augmented.py. 
There is no class named FusionNet, so I think there is a slight typo there.

I appreciate your help.
thanks,

```
/home/eminozkan/anaconda3/envs/torch/bin/python /home/eminozkan/PycharmProjects/FusionNet_Pytorch/main_augmented.py
Traceback (most recent call last):
  File "/home/eminozkan/PycharmProjects/FusionNet_Pytorch/main_augmented.py", line 26, in <module>
    fusion = nn.DataParallel(FusionNet()).cuda()
NameError: name 'FusionNet' is not defined
```

**Comment by GunhoChoi** [comment]
Oh there was a typo I have changed that line into 

fusion = nn.DataParallel(FusionGenerator(3,3,16)).cuda()

It should be working now!

**Comment by emindeniz** [comment]
Ok, Thanks. It works.
